### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by rommyk** [rommyk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by baron1xxx** [comment]
**― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.**

**Comment by rommyk** [comment]
Дякую!!!

**Comment by baron1xxx** [comment]
<h2>Résumé</h2>
<p>&mdash; I do not compete with others
<strong style="margin-left: 0.0625em;">*</strong> , the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.</p>

**Comment by baron1xxx** [comment]
**Avatar**
```
<div class="avatar-wrapper">
 <object class="avatar" data="./assets/images/avatar.svg" role="img"
 aria-label="My profile picture"></object>
</div
```
