### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by rommyk** [rommyk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by baron1xxx** [comment]
## LANGUAGES
:us: ENGLISH :cn: MANDARIN :jp: JAPANESE

### SKILLS
KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT PLAYING VIDEOGAMES DOING BURGERS MASHING POTATOES COPYWRITING ACTING VOICEOVERS

### CHARACTER
NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE

### LIFE LESSON
You must defeat Sheng Long to stand a chance.

### LIKES :smiley:
GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY

### DISLIKES :disappointed:
BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD BARBER SHOPS SLEEVES

### WANTS :pleading_face:
BE FIT WRITE MORE BOOKS FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY

**Comment by rommyk** [comment]
Супер.

**Comment by baron1xxx** [comment]
###  Languages
                        <section>
                            <h3>Languages</h3>
                            <p class="tags small">
                                <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span>
                                <span class="language" lang="en">&#x1f1e8;&#x1f1f1; MANDARIN</span>
                                <span class="language" lang="en">&#x1f1ef;&#x1f1f5; JAPANESE</span>
                            </p>
                        </section>
### Skills
                        <section>
                            <h3>Skills</h3>
                            <p class="tags small">
                                KARATE ENERGY ATTACK SHORYUKEN WALKING BAREFOOT <span
                                    class="nowrap">PLAYING VIDEOGAMES</span>
                                DOING BURGERS <span class="nowrap">MASHING POTATOES</span> 
                                COPYWRITING ACTING VOICEOVERS
                            </p>
                        </section>

### Achievements
                        <section>
                            <h3>Achievements</h3>
                            <ul>
                                <li>#1 in <strong>"Top 25 Street Fighter Characters"</strong> by IGN, who also called me
                                    "fancy", "icon" and "a testament to the virtue of simplicity" &#x2764;
                                </li>
                                <li>#2 in <strong>"Top 20 Street Fighter Characters of All Time"</strong> by GameDaily,
                                    same council found me worth of #6 place in <strong>"Top 25 Capcom Characters of All
                                        Time"</strong>, which I proudly share with my partner Ken
                                </li>
                                <li>I was named <strong>"5th Most Powerful Street Fighter Character"</strong> by Screen
                                    Rant-san
                                </li>
                                <li>#71 in <strong>"Top 100 Heroes of All Time"</strong> by UGO Networks, also
                                    recognized #2 in their list of <strong>"Top 50 Street Fighter Characters"</strong>
                                </li>
                                <li>In a survey of 4000 online matches for <strong>Super Street Fighter IV</strong>, I
                                    got to be the most popular character, with 16.6% of players choosing my
                                    side
                                </li>
                            </ul>
                        </section>

<section>

### Character
                            <h3>Character</h3>
                            <p class="tags small">
                                NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE
                            </p>
                        </section>


### Life lesson
                        <section>
                            <h3>Life lesson</h3>
                            <p class="tags small">
                                YOU MUST DEFEAT SHENG LONG TO STAND A CHANCE.
                            </p>
                        </section>


 ### Likes
                        <section>
                            <h3>Likes&#x1f603;</h3>
                            <p class="tags small">
                                GI VEGETABLES BLOOD SMALL MARSHMELLOWS RED COLOR KILLED ENEMY
                            </p>
                        </section>
### Dislikes
                        <section>
                            <h3>Dislikes&#x1f61e;</h3>
                            <p class="tags small">
                                BISONS GHOSTS SMARTPHONES SMELL OF SEAFOOD
                                <span class="nowrap">BARBER SHOPS SLEEVES</span>
                            </p>
                        </section>


### Wants
                        <section>
                            <h3>Wants&#x1f97a;</h3>
                            <p class="tags small bulleted">
                                <span class="tag">BE FIT</span>
                                <span class="tag">WRITE MORE BOOKS</span>
                                <span class="tag">FIND A GIRLFRIEND</span>
                                <span class="tag">TO GO TO CINEMA WITH KILL ALL OF AKUMA 
                                FAMILY</span>
                            </p>
                        </section>


### Life & education
                        <section>
                            <h3>Life & education</h3>
                            <p class="tags small">
                                TO LIVE IS TO FIGHT AND TO FIGHT IS TO LIVE. I STARTED LEARNING FIGHTING 
                                AT MY MASTER
                                GOUKEN'S CASTLE, I WAS BEATEN AT HEAD WAY TOO OFTEN TO REMEMBER 
                                WHEN EXACTLY.
                            </p>
                        </section>


### Publications
                        <section>
                            <h3>Publications</h3>
                            <ul>
                                <li>2011 The true and humble story of me under pseudonim <strong>Tyler 
                                 Wilde</strong>
                                    in an article<strong>"The evolution of Ken and Ryu"</strong>
                                </li>
                                <li>2003-2018 For 15 years I have published comic books with <strong>Udon
                                    Entertainment</strong> depicting my adventures, bitter lessons and great 
                                    victories.
                                </li>
                            </ul>
                        </section>
